server.port=8081
spring.application.name=ms-lib-libros

spring.datasource.url=jdbc:mysql://localhost:3306/db_libros
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
